# Define variables
RESOURCE_GROUP_NAME="AzureDevOps"
VM_NAME="DevOpsVM"
ADMIN_USERNAME="azureuser"
ADMIN_PASSWORD="Passw0rd@098765"
VM_SIZE="Standard_B1s"      # Cost-effective, good for basic testing
LOCATION="eastus"           # You can switch to a closer region, e.g. "westus2"

# Create resource group
# az group create --name $RESOURCE_GROUP_NAME --location $LOCATION

# Create VM
az vm create \
  --resource-group $RESOURCE_GROUP_NAME \
  --name $VM_NAME \
  --image Ubuntu2204 \
  --size $VM_SIZE \
  --admin-username $ADMIN_USERNAME \
  --admin-password $ADMIN_PASSWORD \
  --authentication-type password

# Get NSG name (auto-generated by VM deployment)
NSG_NAME=$(az network nsg list --resource-group $RESOURCE_GROUP_NAME --query "[0].name" -o tsv)

# Open SSH with priority 100
az network nsg rule create \
  --resource-group $RESOURCE_GROUP_NAME \
  --nsg-name $NSG_NAME \
  --name allow-ssh \
  --priority 100 \
  --direction Inbound \
  --access Allow \
  --protocol Tcp \
  --destination-port-range 22 \
  --source-address-prefix '*' \
  --destination-address-prefix '*'

# Open HTTP with priority 110
az network nsg rule create \
  --resource-group $RESOURCE_GROUP_NAME \
  --nsg-name $NSG_NAME \
  --name allow-http \
  --priority 110 \
  --direction Inbound \
  --access Allow \
  --protocol Tcp \
  --destination-port-range 80 \
  --source-address-prefix '*' \
  --destination-address-prefix '*'
