#cloud-config
# This section ensures the directory exists, if it's not already created by Packer
write_files:
  - path: - /opt/web/index.html # Create a dummy file or ensure directory, if needed
    permissions: '0644'
    content: |
      This is a placeholder.

runcmd:
  # Get the actual hostname of the deployed VM
  - VM_HOSTNAME=$(hostname)
  # Write the dynamic content to index.html
  - echo "<h1>Hello World</h1> - from VM: $VM_HOSTNAME!</h1>" | sudo tee /opt/web/index.html
  # Restart BusyBox to ensure it serves the new index.html
  - sudo systemctl restart busybox-webserver.service
